export const Europe = [
  'Russia',
  'Germany',
  'England',
  'Scotland',
  'Wales',
  'Republic of Ireland',
  'Northern Ireland',
  'France',
  'Italy',
  'Spain',
  'Ukraine',
  'Poland',
  'Romania',
  'Netherlands',
  'Belgium',
  'Czech Republic',
  'Greece',
  'Portugal',
  'Sweden',
  'Hungary',
  'Belarus',
  'Austria',
  'Serbia',
  'Switzerland',
  'Bulgaria',
  'Denmark',
  'Finland',
  'Slovakia',
  'Norway',
  'Ireland',
  'Croatia',
  'Moldova',
  'Bosnia and Herzegovina',
  'Bosnia-Herzegovina',
  'Albania',
  'Lithuania',
  'North Macedonia',
  'Slovenia',
  'Latvia',
  'Estonia',
  'Montenegro',
  'Luxembourg',
  'Malta',
  'Iceland',
  'Andorra',
  'Monaco',
  'Liechtenstein',
  'San Marino',
  'Holy See',
  'Turkey',
  'Kosovo',
];

export const SouthAmerica = [
  'Argentina',
  'Bolivia',
  'Bouvet Island',
  'Brazil',
  'Chile',
  'Colombia',
  'Ecuador',
  'Falkland Islands',
  'French Guiana',
  'Guyana',
  'Paraguay',
  'Peru',
  'Suriname',
  'Uruguay',
  'Venezuela',
];

export const Africa = [
  'Nigeria',
  'Ethiopia',
  'Democratic Republic of the Congo',
  'Egypt',
  'South Africa',
  'Tanzania',
  'Kenya',
  'Algeria',
  'Uganda',
  'Sudan',
  'Morocco',
  'Angola',
  'Ghana',
  'Cameroon',
  'Madagascar',
  'Mozambique',
  'Ivory Coast',
  "Cote d'Ivoire",
  'Niger',
  'Mali',
  'Malawi',
  'Burkina Faso',
  'Chad',
  'Somalia',
  'Zimbabwe',
  'Zambia',
  'Senegal',
  'South Sudan',
  'Rwanda',
  'Guinea',
  'Benin',
  'Tunisia',
  'Burundi',
  'Sierra Leone',
  'Togo',
  'Libya',
  'Republic of the Congo',
  'DR Congo',
  'Liberia',
  'Central African Republic',
  'Mauritania',
  'Eritrea',
  'Namibia',
  'Gambia',
  'Botswana',
  'Gabon',
  'Lesotho',
  'Guinea-Bissau',
  'Equatorial Guinea',
  'Mauritius',
  'Eswatini',
  'Djibouti',
  'Réunion',
  'Comoros',
  'Cape Verde',
  'Western Sahara',
  'Mayotte',
  'São Tomé and Príncipe',
  'Seychelles',
];

export const NorthAmerica = [
  'United States',
  'Mexico',
  'Canada',
  'Guatemala',
  'Cuba',
  'Haiti',
  'Dominican Republic',
  'Honduras',
  'Nicaragua',
  'El Salvador',
  'Costa Rica',
  'Panama',
  'Jamaica',
  'Trinidad and Tobago',
  'Belize',
  'Bahamas',
  'Barbados',
  'Saint Lucia',
  'Grenada',
  'Antigua and Barbuda',
  'Dominica',
  'Saint Kitts and Nevis',
];

export const Asia = [
  'China',
  'India',
  'Kazakhstan*',
  'Saudi Arabia',
  'Iran',
  'Mongolia',
  'Indonesia',
  'Pakistan',
  'Myanmar',
  'Afghanistan',
  'Yemen',
  'Thailand',
  'Turkmenistan',
  'Uzbekistan',
  'Iraq',
  'Japan',
  'Vietnam',
  'Malaysia',
  'Oman',
  'Philippines',
  'Laos',
  'Kyrgyzstan',
  'Syria',
  'Cambodia',
  'Bangladesh',
  'Nepal',
  'Tajikistan',
  'North Korea',
  'South Korea',
  'Korea, South',
  'Jordan',
  'United Arab Emirates',
  'Azerbaijan*',
  'Georgia*',
  'Sri Lanka',
  'Egypt*',
  'Bhutan',
  'Taiwan',
  'Armenia*',
  'Israel',
  'Kuwait',
  'East Timor',
  'Qatar',
  'Lebanon',
  'Cyprus*',
  'Palestine',
  'Brunei',
  'Bahrain',
  'Singapore',
  'Maldives',
];

export const Australia = ['Austrailia', 'New Zealand', 'Fiji'];
